# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: gouwestadfd 
description: Gouwestad FD
url: http://www.gouwestadfd.nl
author:
  name: Gouwestad Marketing en Media
  email: lex@gouwestad.com

include: ['.htaccess']

# -----
# Build

assets:
  compress:
    js: false
  digest: true

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - components/bootstrap/docs
  - components/bootstrap/index.html
  - sass
  - css


# Markdown library
markdown: kramdown
#   extensions: ['fenced_code_blocks', 'smart']

host:             0.0.0.0

## Style Options in posts

collections:
 producten:
  output: true
