# Jekyll configuration precedence:
# 1. Gruntfile task
# 2. config.build.yml
# 3. config.yml

name: gouwestadfd 
description: Gouwestad FD
url: http://www.gouwestadfd.nl
author:
  name: Gouwestad Marketing en Media
  email: lex@gouwestad.com

include: ['.htaccess']

# -----
# Build

assets:
  compress:
    js: false
  digest: true

plugins:
  - jekyll-archives
  - jekyll-sitemap
  - jekyll-seo-tag
  - jekyll-feed
  - jekyll-paginate
  - jekyll-assets

exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - LICENCE
  - components/bootstrap/docs
  - components/bootstrap/index.html
  - components

# Markdown library
markdown: kramdown
#   extensions: ['fenced_code_blocks', 'smart']

host:             0.0.0.0

_options:
  some_markdown:
    bold: true
    table: true
  _text:
    italic: true
  _block:
    format: p h3 d-flex
    undo: true
    redo: true
  content:
    format: p h1 h2 h3 h4 h5 h6 pre address div
    bold: true
    numberedlist: true
    code: true
    table: true
    right: align-to-right
    styles: /css/content.css
